name: CMake Ubuntu (Vulkan)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Dependencies
        run: sudo apt-get install libglfw3 libglfw3-dev libglm-dev libvulkan-dev vulkan-validationlayers-dev spirv-tools libopenal-dev && brew install glslang

      - name: Cache Cmake Build
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-vulkan

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}