name: CMake Windows (Vulkan)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Conan
        run: pip install conan

      - name: Cache Conan Dependencies
        id: cache-conan
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\.conan2
          key: ${{runner.os}}-conan-${{hashFiles('**/conan_vk.txt')}}

      #if we don't hit the cache we need to create a conan default profile
      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: Create default profile
        run: conan profile detect

      - name: Install Dependencies
        run: conan install ${{github.workspace}}\conan_vk.txt -s build_type=${{env.BUILD_TYPE}} --build=missing

      - name: Cache CMake Build
        id: cache-cmake
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}\build
          key: ${{runner.os}}-cmake-${{hashFiles('**/CMakeLists.txt')}}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}\build\generators\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}
